import type { WordPack } from "~/types/wordPairs";

export const wordPacks: WordPack[] = [
  {
    name: "Cibo e Bevande",
    icon: "🍔",
    pairs: [
      { civilian: "Mela", undercover: "Pera" },
      { civilian: "Pizza", undercover: "Focaccia" },
      { civilian: "Latte", undercover: "Yogurt" },
      { civilian: "Pasta", undercover: "Riso" },
      { civilian: "Pane", undercover: "Grissino" },
      { civilian: "Formaggio", undercover: "Burro" },
      { civilian: "Bistecca", undercover: "Salsiccia" },
      { civilian: "Salmone", undercover: "Tonno" },
      { civilian: "Uovo all'occhio di bue", undercover: "Uovo sodo" },
      { civilian: "Pomodoro", undercover: "Patata" },
      { civilian: "Carota", undercover: "Zucchina" },
      { civilian: "Insalata", undercover: "Spinaci" },
      { civilian: "Arancia", undercover: "Limone" },
      { civilian: "Anguria", undercover: "Melone" },
      { civilian: "Fragola", undercover: "Lampone" },
      { civilian: "Zucchero", undercover: "Sale" },
      { civilian: "Olio", undercover: "Aceto" },
      { civilian: "Vino rosso", undercover: "Vino bianco" },
      { civilian: "Acqua", undercover: "Succo di frutta" },
      { civilian: "Torta", undercover: "Biscotto" },
      { civilian: "Gelato", undercover: "Granita" },
      { civilian: "Cioccolato fondente", undercover: "Cioccolato al latte" },
      { civilian: "Caffè espresso", undercover: "Caffè americano" },
      { civilian: "Minestra", undercover: "Zuppa" },
      { civilian: "Patatine fritte", undercover: "Patatine in busta" },
      { civilian: "Popcorn", undercover: "Nachos" },
      { civilian: "Ketchup", undercover: "Maionese" },
      { civilian: "Pranzo", undercover: "Cena" },
      { civilian: "Prosecco", undercover: "Champagne" },
      { civilian: "Birra", undercover: "Vino" },
      { civilian: "Tiramisù", undercover: "Panna cotta" },
      { civilian: "Lasagna", undercover: "Cannelloni" },
      { civilian: "Spaghetti", undercover: "Rigatoni" },
      { civilian: "Limoncello", undercover: "Grappa" },
      { civilian: "Panettone", undercover: "Pandoro" },
      { civilian: "Prosciutto crudo", undercover: "Prosciutto cotto" },
      { civilian: "Tè", undercover: "Camomilla" },
      { civilian: "Parmigiano", undercover: "Pecorino" },
      { civilian: "Salame", undercover: "Mortadella" },
      { civilian: "Pollo", undercover: "Tacchino" },
      { civilian: "Miele", undercover: "Marmellata" },
      { civilian: "Cappuccino", undercover: "Latte macchiato" },
      { civilian: "Melanzana", undercover: "Peperone" },
      { civilian: "Caffettiera", undercover: "Teiera" },
      { civilian: "Grattugia", undercover: "Scolapasta" },
      { civilian: "Mattarello", undercover: "Frusta" },
      { civilian: "Risotto", undercover: "Paella" },
      { civilian: "Prezzemolo", undercover: "Basilico" },
      { civilian: "Noce", undercover: "Mandorla" },
      { civilian: "Mandarino", undercover: "Clementina" },
      { civilian: "Ghiacciolo", undercover: "Sorbetto" },
      { civilian: "Rucola", undercover: "Lattuga" },
      { civilian: "Zucchero a velo", undercover: "Farina" },
      { civilian: "Gnocchi", undercover: "Ravioli" },
      { civilian: "Mostarda", undercover: "Senape" },
      { civilian: "Spritz", undercover: "Negroni" },
      { civilian: "Uva", undercover: "Ciliegia" },
      { civilian: "Pesca", undercover: "Albicocca" },
      { civilian: "Carciofo", undercover: "Finocchio" },
      { civilian: "Caffè", undercover: "Tè" },
      { civilian: "Acqua frizzante", undercover: "Acqua tonica" },
      { civilian: "Pesto", undercover: "Sugo" },
      { civilian: "Mozzarella", undercover: "Ricotta" },
      { civilian: "Vongola", undercover: "Cozza" },
      { civilian: "Crema pasticcera", undercover: "Crema chantilly" },
      { civilian: "Aranciata", undercover: "Limonata" },
      { civilian: "Polenta", undercover: "Purè" },
      { civilian: "Ciambella", undercover: "Bombolone" },
      { civilian: "Mandorla", undercover: "Pistacchio" },
    ],
  },
  {
    name: "Animali",
    icon: "🐶",
    pairs: [
      { civilian: "Cane", undercover: "Gatto" },
      { civilian: "Cane", undercover: "Lupo" },
      { civilian: "Cavallo", undercover: "Asino" },
      { civilian: "Mucca", undercover: "Pecora" },
      { civilian: "Maiale", undercover: "Gallina" },
      { civilian: "Leone", undercover: "Tigre" },
      { civilian: "Elefante", undercover: "Giraffa" },
      { civilian: "Scimmia", undercover: "Gorilla" },
      { civilian: "Pappagallo", undercover: "Canarino" },
      { civilian: "Pinguino", undercover: "Foca" },
      { civilian: "Serpente", undercover: "Lucertola" },
      { civilian: "Ragno", undercover: "Scorpione" },
      { civilian: "Ape", undercover: "Vespa" },
      { civilian: "Farfalla", undercover: "Libellula" },
      { civilian: "Formica", undercover: "Coccinella" },
      { civilian: "Delfino", undercover: "Balena" },
      { civilian: "Squalo", undercover: "Orca" },
      { civilian: "Granchio", undercover: "Gambero" },
      { civilian: "Polpo", undercover: "Calamaro" },
      { civilian: "Coniglio", undercover: "Lepre" },
      { civilian: "Topo", undercover: "Ratto" },
      { civilian: "Rana", undercover: "Rospo" },
      { civilian: "Aquila", undercover: "Falco" },
      { civilian: "Zanzara", undercover: "Mosca" },
      { civilian: "Corvo", undercover: "Piccione" },
      { civilian: "Medusa", undercover: "Stella marina" },
      { civilian: "Cammello", undercover: "Dromedario" },
      { civilian: "Grillo", undercover: "Cavalletta" },
      { civilian: "Gabbiano", undercover: "Piccione" },
      { civilian: "Tartaruga", undercover: "Lumaca" },
      { civilian: "Rondine", undercover: "Pipistrello" },
      { civilian: "Rinoceronte", undercover: "Ippopotamo" },
      { civilian: "Corna", undercover: "Zanna" },
      { civilian: "Piuma", undercover: "Squama" },
      { civilian: "Riccio", undercover: "Istrice" },
      { civilian: "Porcospino", undercover: "Istrice" },
      { civilian: "Vespa", undercover: "Calabrone" },
    ],
  },
  {
    name: "Oggetti",
    icon: "🛋️",
    pairs: [
      { civilian: "Sedia", undercover: "Poltrona" },
      { civilian: "Libro", undercover: "Fumetto" },
      { civilian: "Letto", undercover: "Amaca" },
      { civilian: "Forchetta", undercover: "Coltello" },
      { civilian: "Forchetta", undercover: "Cucchiaio" },
      { civilian: "Lampadina", undercover: "Candela" },
      { civilian: "Zaino", undercover: "Valigia" },
      { civilian: "Penna", undercover: "Matita" },
      { civilian: "Quaderno", undercover: "Agenda" },
      { civilian: "Forbici", undercover: "Taglierino" },
      { civilian: "Colla", undercover: "Nastro adesivo" },
      { civilian: "Moneta", undercover: "Banconota" },
      { civilian: "Chiave", undercover: "Lucchetto" },
      { civilian: "Martello", undercover: "Cacciavite" },
      { civilian: "Chiodo", undercover: "Vite" },
      { civilian: "Bicchiere", undercover: "Calice" },
      { civilian: "Padella", undercover: "Pentola" },
      { civilian: "Forno", undercover: "Microonde" },
      { civilian: "Anello", undercover: "Bracciale" },
      { civilian: "Chitarra", undercover: "Violino" },
      { civilian: "Pianoforte", undercover: "Organo" },
      { civilian: "Flauto", undercover: "Tromba" },
      { civilian: "Pennello", undercover: "Spatola" },
      { civilian: "Calamita", undercover: "Bussola" },
      { civilian: "Stivale", undercover: "Mocassino" },
      { civilian: "Scrivania", undercover: "Tavolo" },
      { civilian: "Asciugamano", undercover: "Accappatoio" },
      { civilian: "Lenzuolo", undercover: "Coperta" },
      { civilian: "Tenda", undercover: "Sacco a pelo" },
      { civilian: "Tazza", undercover: "Tazzina da Caffè" },
      { civilian: "Pinza", undercover: "Tenaglia" },
      { civilian: "Tamburo", undercover: "Piatto" },
      { civilian: "Termometro", undercover: "Barometro" },
      { civilian: "Bandiera", undercover: "Stendardo" },
      { civilian: "Tappeto", undercover: "Moquette" },
      { civilian: "Cuscino", undercover: "Piumone" },
      { civilian: "Vaso", undercover: "Fioriera" },
      { civilian: "Sedia a dondolo", undercover: "Sedia a sdraio" },
      { civilian: "Bambola", undercover: "Peluche" },
      { civilian: "Sgabello", undercover: "Pouf" },
      { civilian: "Freccia", undercover: "Dardo" },
      { civilian: "Saponetta", undercover: "Sapone liquido" },
      { civilian: "Dentifricio", undercover: "Collutorio" },
      { civilian: "Sega", undercover: "Ascia" },
      { civilian: "Trapano", undercover: "Avvitatore" },
      { civilian: "Fazzoletto", undercover: "Tovagliolo" },
      { civilian: "Collana", undercover: "Orecchino" },
      { civilian: "Gemelli", undercover: "Fermacravatta" },
      { civilian: "Francobollo", undercover: "Busta" },
      { civilian: "Scopa", undercover: "Mocio" },
      { civilian: "Zerbino", undercover: "Tappeto" },
      { civilian: "Lampadario", undercover: "Lampada da Letto" },
      { civilian: "Comodino", undercover: "Cassettone" },
      { civilian: "Spilla", undercover: "Fermaglio" },
      { civilian: "Borsa", undercover: "Portafoglio" },
      { civilian: "Binocolo", undercover: "Telescopio" },
      { civilian: "Bottiglia", undercover: "Fiasco" },
      { civilian: "Inchiostro", undercover: "Vernice" },
      { civilian: "Scettro", undercover: "Bastone" },
      { civilian: "Timbro", undercover: "Sigillo" },
      { civilian: "Scatola", undercover: "Cofanetto" },
      { civilian: "Fiala", undercover: "Ampolla" },
      { civilian: "Barattolo", undercover: "Lattina" },
      { civilian: "Tagliere", undercover: "Vassoio" },
      { civilian: "Cerotto", undercover: "Garza" },
      { civilian: "Carriola", undercover: "Carrello" },
      { civilian: "Ciambella salvagente", undercover: "Giubbotto di salvataggio" },
      { civilian: "Corda", undercover: "Catena" },
      { civilian: "Pila", undercover: "Batteria" },
      { civilian: "Spugna", undercover: "Panno" },
      { civilian: "Porta", undercover: "Finestra" },
      { civilian: "Muro", undercover: "Recinzione" },
      { civilian: "Pavimento", undercover: "Soffitto" },
      { civilian: "Armadio", undercover: "Cassettiera" },
      { civilian: "Tapparella", undercover: "Persiana" },
      { civilian: "Scarpa", undercover: "Ciabatta" },
      { civilian: "Maglietta", undercover: "Canottiera" },
      { civilian: "Occhiali da sole", undercover: "Occhiali da vista" },
      { civilian: "Orologio da polso", undercover: "Sveglia" },
      { civilian: "Gonna", undercover: "Vestito" },
      { civilian: "Giacca", undercover: "Cappotto" },
      { civilian: "Calzino", undercover: "Calze da Donna" },
      { civilian: "Cintura", undercover: "Bretelle" },
      { civilian: "Camicia", undercover: "Polo" },
      { civilian: "Pigiama", undercover: "Camicia da notte" },
      { civilian: "Impermeabile", undercover: "Ombrello" },
      { civilian: "Costume da bagno", undercover: "Abbigliamento intimo" },
      { civilian: "Felpa", undercover: "Maglione" },
      { civilian: "Cappello", undercover: "Berretto" },
      { civilian: "Sandalo", undercover: "Infradito" },
      { civilian: "Gilet", undercover: "Camicia" },
      { civilian: "Bikini", undercover: "Costume intero" },
    ],
  },
  {
    name: "Cultura e Svago",
    icon: "🎭",
    pairs: [
      { civilian: "Film", undercover: "Serie TV" },
      { civilian: "Fotografia", undercover: "Video" },
      { civilian: "Notizia", undercover: "Gossip" },
      { civilian: "Internet", undercover: "Televisione" },
      { civilian: "Facebook", undercover: "Instagram" },
      { civilian: "Netflix", undercover: "Prime Video" },
      { civilian: "Harry Potter", undercover: "Signore degli Anelli" },
      { civilian: "Telegiornale", undercover: "Documentario" },
      { civilian: "Vignetta", undercover: "Caricatura" },
      { civilian: "Diario", undercover: "Blog" },
      { civilian: "Commedia", undercover: "Tragedia" },
      { civilian: "Burattino", undercover: "Marionetta" },
      { civilian: "Copione", undercover: "Spartito musicale" },
      { civilian: "Stampa", undercover: "Manoscritto" },
      { civilian: "Padel", undercover: "Tennis" },
      { civilian: "Calcio", undercover: "Rugby" },
      { civilian: "Vela", undercover: "Surf" },
      { civilian: "Scacchi", undercover: "Dama" },
      { civilian: "Basket", undercover: "Pallavolo" },
      { civilian: "Sci", undercover: "Snowboard" },
      { civilian: "Briscola", undercover: "Scopa" },
      { civilian: "Pattinaggio", undercover: "Hockey" },
      { civilian: "Monopoli", undercover: "Risiko" },
      { civilian: "Cruciverba", undercover: "Sudoku" },
      { civilian: "Biliardo", undercover: "Bocce" },
      { civilian: "Canto", undercover: "Ballo" },
      { civilian: "Fantasma", undercover: "Zombie" },
      { civilian: "Mago", undercover: "Strega" },
      { civilian: "Fata", undercover: "Elfo" },
      { civilian: "Spada", undercover: "Scudo" },
      { civilian: "Castello", undercover: "Caverna" },
      { civilian: "Tesoro", undercover: "Mappa" },
      { civilian: "Pirata", undercover: "Ninja" },
      { civilian: "Robot", undercover: "Alieno" },
      { civilian: "Supereroe", undercover: "Cattivo" },
      { civilian: "Mito", undercover: "Favola" },
      { civilian: "Armatura", undercover: "Elmo" },
      { civilian: "Arco", undercover: "Balestra" },
      { civilian: "Scudo", undercover: "Corazza" },
    ],
  },
  {
    name: "Concetti Astratti",
    icon: "🤔",
    pairs: [
      { civilian: "Storia", undercover: "Leggenda" },
      { civilian: "Matematica", undercover: "Scienze" },
      { civilian: "Lavoro", undercover: "Hobby" },
      { civilian: "Sogno", undercover: "Incubo" },
      { civilian: "Domanda", undercover: "Risposta" },
      { civilian: "Bugia", undercover: "Verità" },
      { civilian: "Regalo", undercover: "Sorpresa" },
      { civilian: "Obiettivo", undercover: "Missione" },
      { civilian: "Fortuna", undercover: "Sfortuna" },
      { civilian: "Luce", undercover: "Ombra" },
      { civilian: "Errore", undercover: "Soluzione" },
      { civilian: "Regola", undercover: "Eccezione" },
      { civilian: "Caldo", undercover: "Freddo" },
      { civilian: "Fame", undercover: "Sete" },
      { civilian: "Risata", undercover: "Pianto" },
      { civilian: "Dolore", undercover: "Piacere" },
      { civilian: "Paura", undercover: "Coraggio" },
      { civilian: "Felicità", undercover: "Tristezza" },
      { civilian: "Rabbia", undercover: "Calma" },
      { civilian: "Paradiso", undercover: "Inferno" },
      { civilian: "Magia", undercover: "Illusione" },
      { civilian: "Poesia", undercover: "Prosa" },
      { civilian: "Rumore", undercover: "Suono" },
      { civilian: "Amore", undercover: "Amicizia" },
      { civilian: "Destino", undercover: "Casualità" },
      { civilian: "Scienza", undercover: "Filosofia" },
      { civilian: "Nostalgia", undercover: "Rimpianto" },
      { civilian: "Dialetto", undercover: "Lingua" },
      { civilian: "Causa", undercover: "Effetto" },
      { civilian: "Teoria", undercover: "Pratica" },
      { civilian: "Talento", undercover: "Impegno" },
      { civilian: "Ricordo", undercover: "Promessa" },
      { civilian: "Sicurezza", undercover: "Certezza" },
      { civilian: "Confine", undercover: "Orizzonte" },
      { civilian: "Vortice", undercover: "Spirale" },
      { civilian: "Codice", undercover: "Formula" },
      { civilian: "Istinto", undercover: "Razionalità" },
      { civilian: "Pace", undercover: "Silenzio" },
      { civilian: "Dubbio", undercover: "Sospetto" },
      { civilian: "Orgoglio", undercover: "Vanità" },
      { civilian: "Onore", undercover: "Dovere" },
      { civilian: "Vittoria", undercover: "Conquista" },
      { civilian: "Eroe", undercover: "Martire" },
      { civilian: "Segreto", undercover: "Mistero" },
      { civilian: "Patto", undercover: "Giuramento" },
      { civilian: "Fede", undercover: "Speranza" },
      { civilian: "Pettegolezzo", undercover: "Voce di corridoio" },
      { civilian: "Istinto", undercover: "Intuizione" },
      { civilian: "Sussurro", undercover: "Soffio" },
      { civilian: "Conoscenza", undercover: "Competenza" },
      { civilian: "Vizio", undercover: "Peccato" },
      { civilian: "Proverbio", undercover: "Modo di dire" },
    ],
  },
  {
    name: "Misto",
    icon: "🎲",
    pairs: [
      { civilian: "Contante", undercover: "Carta di Credito" },
      { civilian: "Password", undercover: "PIN" },
      { civilian: "Estate", undercover: "Inverno" },
      { civilian: "Specchio", undercover: "Vetro" },
      { civilian: "Maschera", undercover: "Travestimento" },
      { civilian: "Puzzle", undercover: "Indovinello" },
      { civilian: "Parola", undercover: "Numero" },
      { civilian: "Re", undercover: "Regina" },
      { civilian: "Carabinieri", undercover: "Polizia" },
      { civilian: "Aperitivo", undercover: "Apericena" },
      { civilian: "Pepe", undercover: "Peperoncino" },
      { civilian: "Cipolla", undercover: "Aglio" },
      { civilian: "Tela", undercover: "Affresco" },
      { civilian: "Città", undercover: "Paese" },
      { civilian: "Romanzo", undercover: "Racconto" },
      { civilian: "Giornale", undercover: "Rivista" },
      { civilian: "Passaporto", undercover: "Carta d'identità" },
      { civilian: "Dipinto", undercover: "Disegno" },
      { civilian: "Fratello", undercover: "Sorella" },
      { civilian: "Applauso", undercover: "Fischio" },
      { civilian: "Viaggio", undercover: "Gita" },
      { civilian: "Secolo", undercover: "Decennio" },
      { civilian: "Computer portatile", undercover: "Computer fisso" },
      { civilian: "Carnevale", undercover: "Halloween" },
      { civilian: "Barca", undercover: "Zattera" },
      { civilian: "Profumo", undercover: "Deodorante" },
      { civilian: "Lettera", undercover: "Email" },
      { civilian: "Tatuaggio", undercover: "Cicatrice" },
      { civilian: "Guardare", undercover: "Sbirciare" },
      { civilian: "Origliare", undercover: "Sentire" },
      { civilian: "Correre", undercover: "Camminare" },
      { civilian: "Firma", undercover: "Sigla" },
      { civilian: "Diploma", undercover: "Laura" },
      { civilian: "Seta", undercover: "Velluto" },
      { civilian: "Lana", undercover: "Cotone" },
      { civilian: "Piuma", undercover: "Pelo" },
      { civilian: "Argilla", undercover: "Gesso" },
      { civilian: "Indizio", undercover: "Prova" },
      { civilian: "Inno", undercover: "Canzone" },
      { civilian: "Laurea", undercover: "Dottorato" },
      { civilian: "Esercito", undercover: "Marina Militare" },
      { civilian: "Inno", undercover: "Preghiera" },
      { civilian: "Aneddoto", undercover: "Barzelletta" },
      { civilian: "Punto", undercover: "Virgola" },
      { civilian: "Mosaico", undercover: "Dipinto" },
      { civilian: "Mosaico", undercover: "Vetrata" },
      { civilian: "Mano", undercover: "Piede" },
      { civilian: "Occhio", undercover: "Orecchio" },
      { civilian: "Naso", undercover: "Bocca" },
      { civilian: "Capelli", undercover: "Barba" },
      { civilian: "Dito", undercover: "Unghia" },
      { civilian: "Cuore", undercover: "Cervello" },
      { civilian: "Spalla", undercover: "Ginocchio" },
      { civilian: "Argine", undercover: "Diga" },
      { civilian: "Sasso", undercover: "Roccia" },
      { civilian: "Ghiaccio", undercover: "Brina" },
      { civilian: "Dottore", undercover: "Infermiere" },
      { civilian: "Giardino", undercover: "Orto" },
      { civilian: "Soppalco", undercover: "Mansarda" },
      { civilian: "Rotonda", undercover: "Incrocio" },
      { civilian: "Albergo", undercover: "Bed & Breakfast" },
      { civilian: "Ghianda", undercover: "Castagna" },
      { civilian: "Statua", undercover: "Busto" },
      { civilian: "Ponte", undercover: "Tunnel" },
      { civilian: "Insegnante", undercover: "Studente" },
      { civilian: "Sole", undercover: "Luna" },
      { civilian: "Architetto", undercover: "Ingegnere" },
      { civilian: "Polvere", undercover: "Cenere" },
      { civilian: "Chiesa", undercover: "Moschea" },
      { civilian: "Motorino", undercover: "Bicicletta" },
      { civilian: "Cinema", undercover: "Teatro" },
      { civilian: "Fabbro", undercover: "Falegname" },
      { civilian: "Scuola", undercover: "Università" },
      { civilian: "Soffitta", undercover: "Taverna" },
      { civilian: "Medico", undercover: "Veterinario" },
      { civilian: "Farmacia", undercover: "Parafarmacia" },
      { civilian: "Aereo", undercover: "Elicottero" },
      { civilian: "Grandine", undercover: "Gelo" },
      { civilian: "Marte", undercover: "Giove" },
      { civilian: "Albergo", undercover: "Ostello" },
      { civilian: "Grattacielo", undercover: "Palazzo" },
      { civilian: "Capanna", undercover: "Bungalow" },
      { civilian: "Ghiacciaio", undercover: "Valanga" },
      { civilian: "Stella", undercover: "Pianeta" },
      { civilian: "Arbitro", undercover: "Giudice" },
      { civilian: "Cantante", undercover: "Musicista" },
      { civilian: "Isola", undercover: "Penisola" },
      { civilian: "Stazione", undercover: "Aeroporto" },
      { civilian: "Prato", undercover: "Campo" },
      { civilian: "Erba", undercover: "Foglia" },
      { civilian: "Spiaggia", undercover: "Scogliera" },
      { civilian: "Ristorante", undercover: "Bar" },
      { civilian: "Poliziotto", undercover: "Pompiere" },
      { civilian: "Giudice", undercover: "Avvocato" },
      { civilian: "Bosco", undercover: "Pineta" },
      { civilian: "Uragano", undercover: "Tornado" },
      { civilian: "Promontorio", undercover: "Montagna" },
      { civilian: "Tastiera", undercover: "Mouse" },
      { civilian: "Esploratore", undercover: "Pioniere" },
      { civilian: "Cuoco", undercover: "Cameriere" },
      { civilian: "Canoa", undercover: "Gondola Veneziana" },
      { civilian: "Pilota", undercover: "Autista" },
      { civilian: "Magazzino", undercover: "Cantina" },
      { civilian: "Marea", undercover: "Corrente marina" },
      { civilian: "Strada", undercover: "Autostrada" },
      { civilian: "Tuono", undercover: "Lampo" },
      { civilian: "Artigiano", undercover: "Operaio" },
      { civilian: "Imperatore", undercover: "Faraone" },
      { civilian: "Carcere", undercover: "Manicomio" },
      { civilian: "Capitano", undercover: "Comandante" },
      { civilian: "Pittore", undercover: "Scultore" },
      { civilian: "Bottega", undercover: "Laboratorio" },
      { civilian: "Pioggia", undercover: "Neve" },
      { civilian: "Mimo", undercover: "Clown" },
      { civilian: "Cortile", undercover: "Chiostro" },
      { civilian: "Fiume", undercover: "Lago" },
      { civilian: "Barca a vela", undercover: "Motoscafo" },
      { civilian: "Barbiere", undercover: "Parrucchiere" },
      { civilian: "Principe", undercover: "Cavaliere" },
      { civilian: "Treno", undercover: "Metropolitana" },
      { civilian: "Balcone", undercover: "Terrazzo" },
      { civilian: "Frullatore", undercover: "Tritacarne" },
      { civilian: "Vulcano", undercover: "Terremoto" },
      { civilian: "Timone", undercover: "Vela" },
      { civilian: "Albero", undercover: "Fiore" },
      { civilian: "Scrittore", undercover: "Giornalista" },
      { civilian: "Rosa", undercover: "Tulipano" },
      { civilian: "Sindaco", undercover: "Presidente" },
      { civilian: "Montagna", undercover: "Collina" },
      { civilian: "Grotta", undercover: "Miniera" },
      { civilian: "Pozzo", undercover: "Fontana" },
      { civilian: "Stalattite", undercover: "Stalagmite" },
      { civilian: "Canale", undercover: "Acquedotto" },
      { civilian: "Piazza", undercover: "Parco" },
      { civilian: "Stadio", undercover: "Palazzetto dello Sport" },
      { civilian: "Monopattino", undercover: "Skateboard" },
      { civilian: "Pompiere", undercover: "Guardia Forestale" },
      { civilian: "Ruota", undercover: "Ingranaggio" },
      { civilian: "Pino", undercover: "Abete" },
      { civilian: "Soldato", undercover: "Mercenario" },
      { civilian: "Autobus", undercover: "Tram" },
      { civilian: "Maggiordomo", undercover: "Autista" },
      { civilian: "Museo", undercover: "Galleria d'arte" },
      { civilian: "Foresta", undercover: "Giungla" },
      { civilian: "Faro", undercover: "Torre" },
      { civilian: "Scogliera", undercover: "Dirupo" },
      { civilian: "Timone", undercover: "Ancora" },
      { civilian: "Farmacista", undercover: "Erborista" },
      { civilian: "Cantiere", undercover: "Fabbrica" },
      { civilian: "Ruscello", undercover: "Torrente" },
      { civilian: "Attore", undercover: "Regista" },
      { civilian: "Oceano", undercover: "Mare" },
      { civilian: "Sentiero", undercover: "Scalinata" },
      { civilian: "Piscina", undercover: "Vasca da bagno" },
      { civilian: "Telefono", undercover: "Tablet" },
      { civilian: "Sabbia", undercover: "Ghiaia" },
      { civilian: "Nuvola", undercover: "Nebbia" },
      { civilian: "Vicolo", undercover: "Viale" },
      { civilian: "Furgone", undercover: "Camion" },
      { civilian: "Supermercato", undercover: "Centro Commerciale" },
      { civilian: "Violino", undercover: "Violoncello" },
      { civilian: "Alba", undercover: "Tramonto" },
      { civilian: "Biblioteca", undercover: "Libreria" },
      { civilian: "Ritmo", undercover: "Melodia" },
      { civilian: "Auto", undercover: "Moto" },
      { civilian: "Fuoco", undercover: "Ghiaccio" },
      { civilian: "Ospedale", undercover: "Clinica privata" },
      { civilian: "Nave", undercover: "Traghetto" },
      { civilian: "Cascata", undercover: "Sorgente" },
      { civilian: "Re", undercover: "Papa" },
      { civilian: "Mattina", undercover: "Pomeriggio" },
      { civilian: "Spia", undercover: "Detective" },
      { civilian: "Vigile", undercover: "Guardia della Finanza" },
      { civilian: "Scialuppa", undercover: "Gommone" },
      { civilian: "Vite", undercover: "Uva" },
      { civilian: "Acquerello", undercover: "Tempera di Matita" },
      { civilian: "Camper", undercover: "Roulotte" },
      { civilian: "Capitano", undercover: "Generale" },
      { civilian: "Navicella", undercover: "Sottomarino" },
    ],
  },
];

export const wordPackNames = wordPacks.map(pack => pack.name);