import type { WordPair } from "~/types/wordPairs";

export const wordPairs: WordPair[] = [
  { civilian: "Mela", undercover: "Pera" },
  { civilian: "Cane", undercover: "Gatto" },
  { civilian: "Cane", undercover: "Lupo" },
  { civilian: "Sole", undercover: "Luna" },
  { civilian: "Marte", undercover: "Giove" },
  { civilian: "Sedia", undercover: "Poltrona" },
  { civilian: "Auto", undercover: "Moto" },
  { civilian: "Libro", undercover: "Fumetto" },
  { civilian: "Letto", undercover: "Amaca" },
  { civilian: "Forchetta", undercover: "Coltello" },
  { civilian: "Forchetta", undercover: "Cucchiaio" },
  { civilian: "Scarpa", undercover: "Ciabatta" },
  { civilian: "Maglietta", undercover: "Canottiera" },
  { civilian: "Occhiali da sole", undercover: "Occhiali da vista" },
  { civilian: "Orologio da polso", undercover: "Sveglia" },
  { civilian: "Porta", undercover: "Finestra" },
  { civilian: "Muro", undercover: "Recinzione" },
  { civilian: "Pavimento", undercover: "Soffitto" },
  { civilian: "Lampadina", undercover: "Candela" },
  { civilian: "Zaino", undercover: "Valigia" },
  { civilian: "Penna", undercover: "Matita" },
  { civilian: "Quaderno", undercover: "Agenda" },
  { civilian: "Forbici", undercover: "Taglierino" },
  { civilian: "Colla", undercover: "Nastro adesivo" },
  { civilian: "Moneta", undercover: "Banconota" },
  { civilian: "Contante", undercover: "Carta di Credito" },
  { civilian: "Chiave", undercover: "Lucchetto" },
  { civilian: "Martello", undercover: "Cacciavite" },
  { civilian: "Chiodo", undercover: "Vite" },
  { civilian: "Tastiera", undercover: "Mouse" },
  { civilian: "Telefono", undercover: "Tablet" },
  { civilian: "Password", undercover: "PIN" },
  { civilian: "Pizza", undercover: "Focaccia" },
  { civilian: "Latte", undercover: "Yogurt" },
  { civilian: "Pasta", undercover: "Riso" },
  { civilian: "Pane", undercover: "Grissino" },
  { civilian: "Formaggio", undercover: "Burro" },
  { civilian: "Bistecca", undercover: "Salsiccia" },
  { civilian: "Salmone", undercover: "Tonno" },
  { civilian: "Uovo all'occhio di bue", undercover: "Uovo sodo" },
  { civilian: "Pomodoro", undercover: "Patata" },
  { civilian: "Carota", undercover: "Zucchina" },
  { civilian: "Insalata", undercover: "Spinaci" },
  { civilian: "Arancia", undercover: "Limone" },
  { civilian: "Anguria", undercover: "Melone" },
  { civilian: "Fragola", undercover: "Lampone" },
  { civilian: "Zucchero", undercover: "Sale" },
  { civilian: "Olio", undercover: "Aceto" },
  { civilian: "Vino rosso", undercover: "Vino bianco" },
  { civilian: "Acqua", undercover: "Succo di frutta" },
  { civilian: "Torta", undercover: "Biscotto" },
  { civilian: "Gelato", undercover: "Granita" },
  { civilian: "Cioccolato fondente", undercover: "Cioccolato al latte" },
  { civilian: "Caffè espresso", undercover: "Caffè americano" },
  { civilian: "Minestra", undercover: "Zuppa" },
  { civilian: "Patatine fritte", undercover: "Patatine in busta" },
  { civilian: "Popcorn", undercover: "Nachos" },
  { civilian: "Ketchup", undercover: "Maionese" },
  { civilian: "Pranzo", undercover: "Cena" },
  { civilian: "Oceano", undercover: "Mare" },
  { civilian: "Spiaggia", undercover: "Scogliera" },
  { civilian: "Pioggia", undercover: "Neve" },
  { civilian: "Fuoco", undercover: "Ghiaccio" },
  { civilian: "Montagna", undercover: "Collina" },
  { civilian: "Fiume", undercover: "Lago" },
  { civilian: "Albero", undercover: "Fiore" },
  { civilian: "Erba", undercover: "Foglia" },
  { civilian: "Nuvola", undercover: "Nebbia" },
  { civilian: "Stella", undercover: "Pianeta" },
  { civilian: "Alba", undercover: "Tramonto" },
  { civilian: "Mattina", undercover: "Pomeriggio" },
  { civilian: "Cavallo", undercover: "Asino" },
  { civilian: "Mucca", undercover: "Pecora" },
  { civilian: "Maiale", undercover: "Gallina" },
  { civilian: "Leone", undercover: "Tigre" },
  { civilian: "Elefante", undercover: "Giraffa" },
  { civilian: "Scimmia", undercover: "Gorilla" },
  { civilian: "Pappagallo", undercover: "Canarino" },
  { civilian: "Pinguino", undercover: "Foca" },
  { civilian: "Serpente", undercover: "Lucertola" },
  { civilian: "Ragno", undercover: "Scorpione" },
  { civilian: "Ape", undercover: "Vespa" },
  { civilian: "Farfalla", undercover: "Libellula" },
  { civilian: "Formica", undercover: "Coccinella" },
  { civilian: "Delfino", undercover: "Balena" },
  { civilian: "Squalo", undercover: "Orca" },
  { civilian: "Granchio", undercover: "Gambero" },
  { civilian: "Polpo", undercover: "Calamaro" },
  { civilian: "Coniglio", undercover: "Lepre" },
  { civilian: "Topo", undercover: "Ratto" },
  { civilian: "Rana", undercover: "Rospo" },
  { civilian: "Tuono", undercover: "Lampo" },
  { civilian: "Nave", undercover: "Traghetto" },
  { civilian: "Aereo", undercover: "Elicottero" },
  { civilian: "Treno", undercover: "Metropolitana" },
  { civilian: "Scuola", undercover: "Università" },
  { civilian: "Ospedale", undercover: "Clinica privata" },
  { civilian: "Supermercato", undercover: "Centro Commerciale" },
  { civilian: "Ristorante", undercover: "Bar" },
  { civilian: "Cinema", undercover: "Teatro" },
  { civilian: "Piscina", undercover: "Vasca da bagno" },
  { civilian: "Ponte", undercover: "Tunnel" },
  { civilian: "Strada", undercover: "Autostrada" },
  { civilian: "Piazza", undercover: "Parco" },
  { civilian: "Giardino", undercover: "Orto" },
  { civilian: "Estate", undercover: "Inverno" },
  { civilian: "Film", undercover: "Serie TV" },
  { civilian: "Fotografia", undercover: "Video" },
  { civilian: "Notizia", undercover: "Gossip" },
  { civilian: "Storia", undercover: "Leggenda" },
  { civilian: "Matematica", undercover: "Scienze" },
  { civilian: "Mito", undercover: "Favola" },
  { civilian: "Re", undercover: "Regina" },
  { civilian: "Lavoro", undercover: "Hobby" },
  { civilian: "Sogno", undercover: "Incubo" },
  { civilian: "Domanda", undercover: "Risposta" },
  { civilian: "Bugia", undercover: "Verità" },
  { civilian: "Regalo", undercover: "Sorpresa" },
  { civilian: "Obiettivo", undercover: "Missione" },
  { civilian: "Fortuna", undercover: "Sfortuna" },
  { civilian: "Luce", undercover: "Ombra" },
  { civilian: "Specchio", undercover: "Vetro" },
  { civilian: "Maschera", undercover: "Travestimento" },
  { civilian: "Puzzle", undercover: "Indovinello" },
  { civilian: "Internet", undercover: "Televisione" },
  { civilian: "Parola", undercover: "Numero" },
  { civilian: "Errore", undercover: "Soluzione" },
  { civilian: "Regola", undercover: "Eccezione" },
  { civilian: "Dottore", undercover: "Infermiere" },
  { civilian: "Insegnante", undercover: "Studente" },
  { civilian: "Poliziotto", undercover: "Pompiere" },
  { civilian: "Cuoco", undercover: "Cameriere" },
  { civilian: "Attore", undercover: "Regista" },
  { civilian: "Cantante", undercover: "Musicista" },
  { civilian: "Scrittore", undercover: "Giornalista" },
  { civilian: "Pilota", undercover: "Autista" },
  { civilian: "Barbiere", undercover: "Parrucchiere" },
  { civilian: "Mano", undercover: "Piede" },
  { civilian: "Occhio", undercover: "Orecchio" },
  { civilian: "Naso", undercover: "Bocca" },
  { civilian: "Capelli", undercover: "Barba" },
  { civilian: "Dito", undercover: "Unghia" },
  { civilian: "Cuore", undercover: "Cervello" },
  { civilian: "Caldo", undercover: "Freddo" },
  { civilian: "Fame", undercover: "Sete" },
  { civilian: "Risata", undercover: "Pianto" },
  { civilian: "Dolore", undercover: "Piacere" },
  { civilian: "Paura", undercover: "Coraggio" },
  { civilian: "Felicità", undercover: "Tristezza" },
  { civilian: "Rabbia", undercover: "Calma" },
  { civilian: "Fantasma", undercover: "Zombie" },
  { civilian: "Mago", undercover: "Strega" },
  { civilian: "Fata", undercover: "Elfo" },
  { civilian: "Spada", undercover: "Scudo" },
  { civilian: "Castello", undercover: "Caverna" },
  { civilian: "Tesoro", undercover: "Mappa" },
  { civilian: "Pirata", undercover: "Ninja" },
  { civilian: "Robot", undercover: "Alieno" },
  { civilian: "Supereroe", undercover: "Cattivo" },
  { civilian: "Padel", undercover: "Tennis" },
  { civilian: "Facebook", undercover: "Instagram" },
  { civilian: "Calcio", undercover: "Rugby" },
  { civilian: "Carabinieri", undercover: "Polizia" },
  { civilian: "Motorino", undercover: "Bicicletta" },
  { civilian: "Prosecco", undercover: "Champagne" },
  { civilian: "Birra", undercover: "Vino" },
  { civilian: "Tiramisù", undercover: "Panna cotta" },
  { civilian: "Lasagna", undercover: "Cannelloni" },
  { civilian: "Spaghetti", undercover: "Rigatoni" },
  { civilian: "Limoncello", undercover: "Grappa" },
  { civilian: "Netflix", undercover: "Prime Video" },
  { civilian: "Harry Potter", undercover: "Signore degli Anelli" },
  { civilian: "Paradiso", undercover: "Inferno" },
  { civilian: "Aperitivo", undercover: "Apericena" },
  { civilian: "Bicchiere", undercover: "Calice" },
  { civilian: "Padella", undercover: "Pentola" },
  { civilian: "Forno", undercover: "Microonde" },
  { civilian: "Pepe", undercover: "Peperoncino" },
  { civilian: "Cipolla", undercover: "Aglio" },
  { civilian: "Gonna", undercover: "Vestito" },
  { civilian: "Anello", undercover: "Bracciale" },
  { civilian: "Chitarra", undercover: "Violino" },
  { civilian: "Pianoforte", undercover: "Organo" },
  { civilian: "Flauto", undercover: "Tromba" },
  { civilian: "Scacchi", undercover: "Dama" },
  { civilian: "Vela", undercover: "Surf" },
  { civilian: "Pennello", undercover: "Spatola" },
  { civilian: "Tela", undercover: "Affresco" },
  { civilian: "Foresta", undercover: "Giungla" },
  { civilian: "Isola", undercover: "Penisola" },
  { civilian: "Vulcano", undercover: "Terremoto" },
  { civilian: "Grotta", undercover: "Miniera" },
  { civilian: "Biblioteca", undercover: "Libreria" },
  { civilian: "Museo", undercover: "Galleria d'arte" },
  { civilian: "Stadio", undercover: "Palazzetto dello Sport" },
  { civilian: "Albergo", undercover: "Ostello" },
  { civilian: "Camper", undercover: "Roulotte" },
  { civilian: "Magia", undercover: "Illusione" },
  { civilian: "Poesia", undercover: "Prosa" },
  { civilian: "Rumore", undercover: "Suono" },
  { civilian: "Lettera", undercover: "Email" },
  { civilian: "Panettone", undercover: "Pandoro" },
  { civilian: "Prosciutto crudo", undercover: "Prosciutto cotto" },
  { civilian: "Armadio", undercover: "Cassettiera" },
  { civilian: "Violino", undercover: "Violoncello" },
  { civilian: "Tè", undercover: "Camomilla" },
  { civilian: "Basket", undercover: "Pallavolo" },
  { civilian: "Sci", undercover: "Snowboard" },
  { civilian: "Pittore", undercover: "Scultore" },
  { civilian: "Amore", undercover: "Amicizia" },
  { civilian: "Città", undercover: "Paese" },
  { civilian: "Autobus", undercover: "Tram" },
  { civilian: "Monopattino", undercover: "Skateboard" },
  { civilian: "Romanzo", undercover: "Racconto" },
  { civilian: "Giornale", undercover: "Rivista" },
  { civilian: "Passaporto", undercover: "Carta d'identità" },
  { civilian: "Farmacia", undercover: "Parafarmacia" },
  { civilian: "Albergo", undercover: "Bed & Breakfast" },
  { civilian: "Aquila", undercover: "Falco" },
  { civilian: "Calamita", undercover: "Bussola" },
  { civilian: "Dipinto", undercover: "Disegno" },
  { civilian: "Fratello", undercover: "Sorella" },
  { civilian: "Ruscello", undercover: "Torrente" },
  { civilian: "Stivale", undercover: "Mocassino" },
  { civilian: "Destino", undercover: "Casualità" },
  { civilian: "Giacca", undercover: "Cappotto" },
  { civilian: "Calzino", undercover: "Calze da Donna" },
  { civilian: "Cintura", undercover: "Bretelle" },
  { civilian: "Scrivania", undercover: "Tavolo" },
  { civilian: "Asciugamano", undercover: "Accappatoio" },
  { civilian: "Lenzuolo", undercover: "Coperta" },
  { civilian: "Tenda", undercover: "Sacco a pelo" },
  { civilian: "Tazza", undercover: "Tazzina da Caffè" },
  { civilian: "Parmigiano", undercover: "Pecorino" },
  { civilian: "Salame", undercover: "Mortadella" },
  { civilian: "Pollo", undercover: "Tacchino" },
  { civilian: "Miele", undercover: "Marmellata" },
  { civilian: "Cappuccino", undercover: "Latte macchiato" },
  { civilian: "Melanzana", undercover: "Peperone" },
  { civilian: "Zanzara", undercover: "Mosca" },
  { civilian: "Corvo", undercover: "Piccione" },
  { civilian: "Medusa", undercover: "Stella marina" },
  { civilian: "Chiesa", undercover: "Moschea" },
  { civilian: "Stazione", undercover: "Aeroporto" },
  { civilian: "Barca a vela", undercover: "Motoscafo" },
  { civilian: "Canoa", undercover: "Gondola Veneziana" },
  { civilian: "Fabbro", undercover: "Falegname" },
  { civilian: "Soldato", undercover: "Mercenario" },
  { civilian: "Principe", undercover: "Cavaliere" },
  { civilian: "Farmacista", undercover: "Erborista" },
  { civilian: "Briscola", undercover: "Scopa" },
  { civilian: "Pattinaggio", undercover: "Hockey" },
  { civilian: "Telegiornale", undercover: "Documentario" },
  { civilian: "Vignetta", undercover: "Caricatura" },
  { civilian: "Diario", undercover: "Blog" },
  { civilian: "Applauso", undercover: "Fischio" },
  { civilian: "Viaggio", undercover: "Gita" },
  { civilian: "Secolo", undercover: "Decennio" },
  { civilian: "Computer portatile", undercover: "Computer fisso" },
  { civilian: "Pinza", undercover: "Tenaglia" },
  { civilian: "Tamburo", undercover: "Piatto" },
  { civilian: "Termometro", undercover: "Barometro" },
  { civilian: "Bandiera", undercover: "Stendardo" },
  { civilian: "Faro", undercover: "Torre" },
  { civilian: "Carcere", undercover: "Manicomio" },
  { civilian: "Cascata", undercover: "Sorgente" },
  { civilian: "Camicia", undercover: "Polo" },
  { civilian: "Pigiama", undercover: "Camicia da notte" },
  { civilian: "Tappeto", undercover: "Moquette" },
  { civilian: "Cuscino", undercover: "Piumone" },
  { civilian: "Vaso", undercover: "Fioriera" },
  { civilian: "Sedia a dondolo", undercover: "Sedia a sdraio" },
  { civilian: "Caffettiera", undercover: "Teiera" },
  { civilian: "Grattugia", undercover: "Scolapasta" },
  { civilian: "Mattarello", undercover: "Frusta" },
  { civilian: "Risotto", undercover: "Paella" },
  { civilian: "Prezzemolo", undercover: "Basilico" },
  { civilian: "Noce", undercover: "Mandorla" },
  { civilian: "Mandarino", undercover: "Clementina" },
  { civilian: "Ghiacciolo", undercover: "Sorbetto" },
  { civilian: "Rucola", undercover: "Lattuga" },
  { civilian: "Zucchero a velo", undercover: "Farina" },
  { civilian: "Pino", undercover: "Abete" },
  { civilian: "Rosa", undercover: "Tulipano" },
  { civilian: "Uragano", undercover: "Tornado" },
  { civilian: "Pozzo", undercover: "Fontana" },
  { civilian: "Cammello", undercover: "Dromedario" },
  { civilian: "Grillo", undercover: "Cavalletta" },
  { civilian: "Gabbiano", undercover: "Piccione" },
  { civilian: "Bambola", undercover: "Peluche" },
  { civilian: "Arbitro", undercover: "Giudice" },
  { civilian: "Medico", undercover: "Veterinario" },
  { civilian: "Mimo", undercover: "Clown" },
  { civilian: "Grattacielo", undercover: "Palazzo" },
  { civilian: "Cantiere", undercover: "Fabbrica" },
  { civilian: "Magazzino", undercover: "Cantina" },
  { civilian: "Soppalco", undercover: "Mansarda" },
  { civilian: "Statua", undercover: "Busto" },
  { civilian: "Acquerello", undercover: "Tempera di Matita" },
  { civilian: "Commedia", undercover: "Tragedia" },
  { civilian: "Burattino", undercover: "Marionetta" },
  { civilian: "Monopoli", undercover: "Risiko" },
  { civilian: "Carnevale", undercover: "Halloween" },
  { civilian: "Barca", undercover: "Zattera" },
  { civilian: "Impermeabile", undercover: "Ombrello" },
  { civilian: "Profumo", undercover: "Deodorante" },
  { civilian: "Scienza", undercover: "Filosofia" },
  { civilian: "Nostalgia", undercover: "Rimpianto" },
];
