import type { WordPair } from "~/types/wordPairs";

export const wordPairs: WordPair[] = [
  { civilian: "Mela", undercover: "Pera" },
  { civilian: "Cane", undercover: "Gatto" },
  { civilian: "Cane", undercover: "Lupo" },
  { civilian: "Sole", undercover: "Luna" },
  { civilian: "Marte", undercover: "Giove" },
  { civilian: "Sedia", undercover: "Poltrona" },
  { civilian: "Auto", undercover: "Moto" },
  { civilian: "Libro", undercover: "Fumetto" },
  { civilian: "Letto", undercover: "Amaca" },
  { civilian: "Forchetta", undercover: "Coltello" },
  { civilian: "Forchetta", undercover: "Cucchiaio" },
  { civilian: "Scarpa", undercover: "Ciabatta" },
  { civilian: "Maglietta", undercover: "Canottiera" },
  { civilian: "Pantaloni", undercover: "Jeans" },
  { civilian: "Occhiali da sole", undercover: "Occhiali da vista" },
  { civilian: "Orologio da polso", undercover: "Sveglia" },
  { civilian: "Porta", undercover: "Finestra" },
  { civilian: "Muro", undercover: "Finestra" },
  { civilian: "Muro", undercover: "Recinzione" },
  { civilian: "Pavimento", undercover: "Soffitto" },
  { civilian: "Lampadina", undercover: "Candela" },
  { civilian: "Zaino", undercover: "Valigia" },
  { civilian: "Penna", undercover: "Matita" },
  { civilian: "Gomma", undercover: "Matita" },
  { civilian: "Quaderno", undercover: "Agenda" },
  { civilian: "Forbici", undercover: "Taglierino" },
  { civilian: "Colla", undercover: "Nastro adesivo" },
  { civilian: "Moneta", undercover: "Banconota" },
  { civilian: "Contante", undercover: "Carta di Credito" },
  { civilian: "Chiave", undercover: "Lucchetto" },
  { civilian: "Martello", undercover: "Cacciavite" },
  { civilian: "Chiodo", undercover: "Vite" },
  { civilian: "Tastiera", undercover: "Mouse" },
  { civilian: "Telefono", undercover: "Tablet" },
  { civilian: "Password", undercover: "PIN" },

  { civilian: "Caffè", undercover: "Cappuccino" },
  { civilian: "Pizza", undercover: "Focaccia" },
  { civilian: "Latte", undercover: "Yogurt" },
  { civilian: "Pasta", undercover: "Riso" },
  { civilian: "Pane", undercover: "Grissino" },
  { civilian: "Cracker", undercover: "Grissino" },
  { civilian: "Formaggio", undercover: "Burro" },
  { civilian: "Bistecca", undercover: "Salsiccia" },
  { civilian: "Salmone", undercover: "Tonno" },
  { civilian: "Uovo all'occhio di bue", undercover: "Uovo sodo" },
  { civilian: "Pomodoro", undercover: "Patata" },
  { civilian: "Carota", undercover: "Zucchina" },
  { civilian: "Insalata", undercover: "Spinaci" },
  { civilian: "Arancia", undercover: "Limone" },
  { civilian: "Anguria", undercover: "Melone" },
  { civilian: "Fragola", undercover: "Lampone" },
  { civilian: "Zucchero", undercover: "Sale" },
  { civilian: "Pepe", undercover: "Sale" },
  { civilian: "Olio", undercover: "Aceto" },
  { civilian: "Vino rosso", undercover: "Vino bianco" },
  { civilian: "Acqua", undercover: "Succo di frutta" },
  { civilian: "Torta", undercover: "Biscotto" },
  { civilian: "Gelato", undercover: "Granita" },
  { civilian: "Cioccolato fondente", undercover: "Cioccolato al latte" },
  { civilian: "Caffè espresso", undercover: "Caffè americano" },
  { civilian: "Minestra", undercover: "Zuppa" },
  { civilian: "Patatine fritte", undercover: "Patatine in busta" },
  { civilian: "Popcorn", undercover: "Nachos" },
  { civilian: "Ketchup", undercover: "Maionese" },
  { civilian: "Ketchup", undercover: "Salsa Barbeque" },
  { civilian: "Pranzo", undercover: "Cena" },

  { civilian: "Oceano", undercover: "Mare" },
  { civilian: "Spiaggia", undercover: "Scogliera" },
  { civilian: "Pioggia", undercover: "Neve" },
  { civilian: "Fuoco", undercover: "Ghiaccio" },
  { civilian: "Montagna", undercover: "Collina" },
  { civilian: "Fiume", undercover: "Lago" },
  { civilian: "Albero", undercover: "Fiore" },
  { civilian: "Erba", undercover: "Foglia" },
  { civilian: "Nuvola", undercover: "Nebbia" },
  { civilian: "Stella", undercover: "Pianeta" },
  { civilian: "Alba", undercover: "Tramonto" },
  { civilian: "Mattina", undercover: "Pomeriggio" },

  { civilian: "Cavallo", undercover: "Asino" },
  { civilian: "Mucca", undercover: "Pecora" },
  { civilian: "Maiale", undercover: "Gallina" },
  { civilian: "Leone", undercover: "Tigre" },
  { civilian: "Elefante", undercover: "Giraffa" },
  { civilian: "Scimmia", undercover: "Gorilla" },
  { civilian: "Pappagallo", undercover: "Canarino" },
  { civilian: "Pinguino", undercover: "Foca" },
  { civilian: "Serpente", undercover: "Lucertola" },
  { civilian: "Ragno", undercover: "Scorpione" },
  { civilian: "Ape", undercover: "Vespa" },
  { civilian: "Farfalla", undercover: "Libellula" },
  { civilian: "Formica", undercover: "Coccinella" },
  { civilian: "Delfino", undercover: "Balena" },
  { civilian: "Squalo", undercover: "Orca" },
  { civilian: "Granchio", undercover: "Gambero" },
  { civilian: "Polpo", undercover: "Calamaro" },
  { civilian: "Coniglio", undercover: "Lepre" },
  { civilian: "Topo", undercover: "Ratto" },
  { civilian: "Rana", undercover: "Rospo" },
  { civilian: "Tuono", undercover: "Lampo" },

  { civilian: "Nave", undercover: "Traghetto" },
  { civilian: "Aereo", undercover: "Elicottero" },
  { civilian: "Treno", undercover: "Metropolitana" },
  { civilian: "Scuola", undercover: "Università" },
  { civilian: "Ospedale", undercover: "Clinica privata" },
  { civilian: "Supermercato", undercover: "Negozio" },
  { civilian: "Ristorante", undercover: "Bar" },
  { civilian: "Cinema", undercover: "Teatro" },
  { civilian: "Piscina", undercover: "Vasca da bagno" },
  { civilian: "Ponte", undercover: "Tunnel" },
  { civilian: "Strada", undercover: "Autostrada" },
  { civilian: "Piazza", undercover: "Parco" },
  { civilian: "Giardino", undercover: "Orto" },

  { civilian: "Estate", undercover: "Inverno" },
  { civilian: "Film", undercover: "Serie TV" },
  { civilian: "Musica", undercover: "Silenzio" },
  { civilian: "Fotografia", undercover: "Video" },
  { civilian: "Notizia", undercover: "Gossip" },
  { civilian: "Storia", undercover: "Leggenda" },
  { civilian: "Matematica", undercover: "Scienze" },
  { civilian: "Mito", undercover: "Favola" },
  { civilian: "Re", undercover: "Regina" },
  { civilian: "Lavoro", undercover: "Hobby" },
  { civilian: "Sogno", undercover: "Incubo" },
  { civilian: "Domanda", undercover: "Risposta" },
  { civilian: "Bugia", undercover: "Verità" },
  { civilian: "Regalo", undercover: "Sorpresa" },
  { civilian: "Obiettivo", undercover: "Missione" },
  { civilian: "Fortuna", undercover: "Sfortuna" },
  { civilian: "Luce", undercover: "Ombra" },
  { civilian: "Specchio", undercover: "Vetro" },
  { civilian: "Maschera", undercover: "Travestimento" },
  { civilian: "Puzzle", undercover: "Indovinello" },
  { civilian: "Internet", undercover: "Televisione" },
  { civilian: "Parola", undercover: "Numero" },
  { civilian: "Errore", undercover: "Soluzione" },
  { civilian: "Regola", undercover: "Eccezione" },

  { civilian: "Dottore", undercover: "Infermiere" },
  { civilian: "Insegnante", undercover: "Studente" },
  { civilian: "Poliziotto", undercover: "Pompiere" },
  { civilian: "Cuoco", undercover: "Cameriere" },
  { civilian: "Attore", undercover: "Regista" },
  { civilian: "Cantante", undercover: "Musicista" },
  { civilian: "Scrittore", undercover: "Giornalista" },
  { civilian: "Pilota", undercover: "Autista" },
  { civilian: "Barbiere", undercover: "Parrucchiere" },

  { civilian: "Mano", undercover: "Piede" },
  { civilian: "Occhio", undercover: "Orecchio" },
  { civilian: "Naso", undercover: "Bocca" },
  { civilian: "Capelli", undercover: "Barba" },
  { civilian: "Dito", undercover: "Unghia" },
  { civilian: "Cuore", undercover: "Cervello" },
  { civilian: "Caldo", undercover: "Freddo" },
  { civilian: "Fame", undercover: "Sete" },
  { civilian: "Risata", undercover: "Pianto" },
  { civilian: "Dolore", undercover: "Piacere" },
  { civilian: "Paura", undercover: "Coraggio" },
  { civilian: "Felicità", undercover: "Tristezza" },
  { civilian: "Rabbia", undercover: "Calma" },

  { civilian: "Fantasma", undercover: "Zombie" },
  { civilian: "Mago", undercover: "Strega" },
  { civilian: "Fata", undercover: "Elfo" },
  { civilian: "Spada", undercover: "Scudo" },
  { civilian: "Castello", undercover: "Caverna" },
  { civilian: "Tesoro", undercover: "Mappa" },
  { civilian: "Pirata", undercover: "Ninja" },
  { civilian: "Robot", undercover: "Alieno" },
  { civilian: "Supereroe", undercover: "Cattivo" },
];
